#!/usr/bin/env python
# coding: utf-8

# # Notebook 2: Anomaly Analysis and Validation
# 
# This notebook analyses and validates the anomaly detection results generated by
# the Isolation Forest and Local Outlier Factor models in the training pipeline
# (Notebook 1). The analysis focuses on the distribution and interpretation of
# anomaly scores, agreement between models, characteristics of the detected
# observations, comparison with business-rule flags, and the identification of
# representative anomalous listings.
# 
# **Scope:**
# - No models are trained here — all scores/flags come from Notebook 1's outputs.
# - Results are loaded from `model_results_full.csv`.
# - Isolation Forest and LOF outputs are analysed individually and jointly.
# - Agreement between both models is quantified.
# - Detected anomalies are characterised (property type, region, numeric profile).
# - Model outputs are contrasted against business-rule flags (external reference,
#   not ground truth).
# - The most relevant / representative cases are examined individually.
# - Reusable tables and figures are exported.
# 
# **Convention reminder (from Notebook 1):** `if_anomaly` and `lof_anomaly` follow
# scikit-learn's convention: **`-1` = anomaly, `1` = normal**. This notebook builds
# boolean helper columns (`is_if_anomaly`, `is_lof_anomaly`) early on to avoid any
# ambiguity in the rest of the analysis.
# 

# ## 1. Load results and verify reproducibility

# ### 1.1 Imports

# In[34]:
import json
import sys
from pathlib import Path
from itertools import combinations

import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from scipy import stats

try:
    display
except NameError:
    display = print

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
plt.style.use("default")

# Resolver la raíz del proyecto (sube 3 niveles: src -> pipeline -> raíz)
ROOT_DIR = Path(__file__).resolve().parent.parent.parent

OUTPUT_DIR = ROOT_DIR / "data" / "results"
FIG_DIR = ROOT_DIR / "reports" / "figures"

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
FIG_DIR.mkdir(parents=True, exist_ok=True)

print("Librerías importadas y directorios configurados.")


# ### 1.2 Load model results

# In[35]:
# Cargar resultados del entrenamiento con separador ';'
results_file = OUTPUT_DIR / "model_results_full.csv"
if not results_file.exists():
    raise FileNotFoundError(f"No se encontró el archivo de resultados en: {results_file}")

df_results = pd.read_csv(results_file, sep=";")
df_min = pd.read_csv(OUTPUT_DIR / "model_results.csv", sep=";")

with open(OUTPUT_DIR / "model_config.json", "r", encoding="utf-8") as f:
    model_config = json.load(f)

print(f"model_results_full.csv shape: {df_results.shape}")
print(df_results.head())

# ### 1.3 Basic verification

# In[ ]:


print("=" * 60)
print("BASIC VERIFICATION")
print("=" * 60)

n_rows, n_cols = df_results.shape
n_duplicates = df_results.duplicated(subset=['id']).sum()
n_null_scores = df_results[['if_score', 'lof_score']].isna().sum().sum()

df_results['is_if_anomaly'] = df_results['if_anomaly'] == -1
df_results['is_lof_anomaly'] = df_results['lof_anomaly'] == -1

n_if_anomalies = df_results['is_if_anomaly'].sum()
n_lof_anomalies = df_results['is_lof_anomaly'].sum()

print(f"Rows:                {n_rows:,}")
print(f"Columns:             {n_cols}")
print(f"Duplicate ids:       {n_duplicates}")
print(f"Null scores:         {n_null_scores}")
print(f"IF anomalies:        {n_if_anomalies:,} ({n_if_anomalies / n_rows:.2%})")
print(f"LOF anomalies:       {n_lof_anomalies:,} ({n_lof_anomalies / n_rows:.2%})")


# ## 2. Overview of model outputs

# ### 2.1 Summary of detected anomalies

# In[38]:


summary_table = pd.DataFrame([
    {'Model': 'Isolation Forest', 'Anomalies': int(n_if_anomalies), 'Percentage': f"{n_if_anomalies / n_rows:.2%}"},
    {'Model': 'LOF', 'Anomalies': int(n_lof_anomalies), 'Percentage': f"{n_lof_anomalies / n_rows:.2%}"},
])
display(summary_table)


# Both models flag close to the same **percentage** of observations. This is a direct consequence of `contamination` being set to the same value for both models during training.
# 

# ## 3. Distribution of anomaly scores

# ### 3.1 Isolation Forest score distribution

# In[39]:


fig, ax = plt.subplots(figsize=(9, 5))
sns.histplot(data=df_results, x='if_score', hue='is_if_anomaly', bins=60,
             palette={True: 'red', False: 'steelblue'}, alpha=0.6, ax=ax)
ax.set_title('Distribution of Isolation Forest anomaly scores')
ax.set_xlabel('IF score (higher = more anomalous)')
ax.set_ylabel('Number of listings')
plt.tight_layout()
plt.savefig(FIG_DIR / "if_score_distribution.png", dpi=150)
#plt.show()


# ### 3.2 LOF score distribution

# In[40]:


fig, ax = plt.subplots(figsize=(9, 5))
sns.histplot(data=df_results, x='lof_score', hue='is_lof_anomaly', bins=60,
             palette={True: 'red', False: 'steelblue'}, alpha=0.6, ax=ax)
ax.set_xlim(df_results['lof_score'].min(), df_results['lof_score'].quantile(0.995))
ax.set_title('Distribution of LOF anomaly scores')
ax.set_xlabel('LOF score (higher = more anomalous)')
ax.set_ylabel('Number of listings')
plt.tight_layout()
plt.savefig(FIG_DIR / "lof_score_distribution.png", dpi=150)
#plt.show()


# ### 3.3 Comparison of score distributions
# 
# **Important:** `if_score` and `lof_score` are **not on a comparable scale** 
# comparing raw values (e.g. `if_score > lof_score`) would be meaningless. What can
# legitimately be compared across models is **ranking**, **percentiles**, **top-k
# membership**, and the **anomaly/normal label**. Rank-based comparisons are done in
# Sections 4 and 5.
# 

# In[ ]:


fig, axes = plt.subplots(1, 2, figsize=(14, 5))
sns.kdeplot(data=df_results, x='if_score', hue='is_if_anomaly',
            palette={True: 'red', False: 'steelblue'}, ax=axes[0], fill=True, alpha=0.4)
axes[0].set_title('IF score density (normal vs anomaly)')

sns.kdeplot(data=df_results, x='lof_score', hue='is_lof_anomaly',
            palette={True: 'red', False: 'steelblue'}, ax=axes[1], fill=True, alpha=0.4)
axes[1].set_xlim(df_results['lof_score'].min(), df_results['lof_score'].quantile(0.995))
axes[1].set_title('LOF score density (normal vs anomaly)')

plt.tight_layout()
plt.savefig(FIG_DIR / "model_score_correlation.png", dpi=150)
#plt.show()


# IF score separates normal/anomaly with a smoother, more continuous cut-off, while LOF anomalies typically sit in a longer, thinner right tail. It is consistent with LOF flagging locally isolated points rather than globally extreme ones.

# ## 4. Agreement between Isolation Forest and LOF

# ### 4.1 Confusion matrix / contingency table

# In[42]:


contingency = pd.crosstab(
    df_results['is_if_anomaly'].map({True: 'IF anomaly', False: 'IF normal'}),
    df_results['is_lof_anomaly'].map({True: 'LOF anomaly', False: 'LOF normal'})
)
display(contingency)


# ### 4.2 Overlap of detected anomalies

# In[43]:


if_anomalies_ids = set(df_results.loc[df_results['is_if_anomaly'], 'id'])
lof_anomalies_ids = set(df_results.loc[df_results['is_lof_anomaly'], 'id'])

intersection = if_anomalies_ids & lof_anomalies_ids
union = if_anomalies_ids | lof_anomalies_ids
if_only = if_anomalies_ids - lof_anomalies_ids
lof_only = lof_anomalies_ids - if_anomalies_ids

jaccard = len(intersection) / len(union) if union else np.nan

print(f"IF anomalies:        {len(if_anomalies_ids):,}")
print(f"LOF anomalies:       {len(lof_anomalies_ids):,}")
print(f"Intersection (both): {len(intersection):,}")
print(f"Union:               {len(union):,}")
print(f"IF-only:             {len(if_only):,}")
print(f"LOF-only:            {len(lof_only):,}")
print(f"Jaccard similarity:  {jaccard:.4f}")


# ### 4.3 Visualisation of agreement

# In[70]:


agreement_counts = pd.Series({
    'Both models': len(intersection),
    'Isolation Forest only': len(if_only),
    'LOF only': len(lof_only)
})

fig, ax = plt.subplots(figsize=(8, 5))
colors = ['#7b2d8e', '#1f77b4', '#d62728']
agreement_counts.plot(kind='bar', color=colors, ax=ax)
ax.set_title('Agreement between Isolation Forest and LOF')
ax.set_ylabel('Number of listings')
for i, v in enumerate(agreement_counts):
    ax.text(i, v, f"{v:,}", ha='center', va='bottom')
plt.xticks(rotation=20, ha='right')
plt.tight_layout()
plt.savefig(FIG_DIR / "model_agreement.png", dpi=150)
#plt.show()

display(agreement_counts.to_frame("n_listings"))


# ## 5. Relationship between model scores

# ### 5.1 Score correlation

# In[ ]:


fig, ax = plt.subplots(figsize=(7, 6))
sample = df_results.sample(min(5000, len(df_results)), random_state=42)
ax.scatter(sample['if_score'], sample['lof_score'], s=8, alpha=0.3, color='steelblue')
ax.set_xlabel('IF score')
ax.set_ylabel('LOF score')
ax.set_title('IF score vs LOF score')
plt.tight_layout()
#plt.show()

pearson_r, pearson_p = stats.pearsonr(df_results['if_score'], df_results['lof_score'])
spearman_r, spearman_p = stats.spearmanr(df_results['if_score'], df_results['lof_score'])

print(f"Pearson correlation:  {pearson_r:.4f} (p={pearson_p:.2e})")
print(f"Spearman correlation: {spearman_r:.4f} (p={spearman_p:.2e})")


# Spearman is the more meaningful figure here: it asks whether the two models produce a similar RANKING of anomalousness, not whether their raw scores agree in magnitude.

# ### 5.2 Rank correlation

# In[ ]:


df_results['if_rank'] = df_results['if_score'].rank(ascending=False)
df_results['lof_rank'] = df_results['lof_score'].rank(ascending=False)

rank_corr, rank_p = stats.spearmanr(df_results['if_rank'], df_results['lof_rank'])
print(f"Spearman correlation between if_rank and lof_rank: {rank_corr:.4f} (p={rank_p:.2e})")


# This is mathematically equivalent to the Spearman correlation on raw scores above, shown explicitly via ranks for clarity and for reuse in Section 11.

# ## 6. Characterisation of detected anomalies
# 
# Define the working subsets and a small helper to recover a categorical variable even if it was one-hot encoded upstream
# 

# In[71]:


df_if = df_results[df_results['is_if_anomaly']]
df_lof = df_results[df_results['is_lof_anomaly']]
df_both = df_results[df_results['is_if_anomaly'] & df_results['is_lof_anomaly']]

print(f"IF anomalies:       {len(df_if):,}")
print(f"LOF anomalies:      {len(df_lof):,}")
print(f"Both (consensus):   {len(df_both):,}")


def get_categorical(frame, prefix):
    if prefix in frame.columns:
        return frame[prefix]
    dummy_cols = [c for c in frame.columns if c.startswith(f"{prefix}_")]
    if dummy_cols:
        return frame[dummy_cols].idxmax(axis=1).str.replace(f"{prefix}_", "", regex=False)
    return None


def category_distribution(prefix, label):
    full_cat = get_categorical(df_results, prefix)
    if full_cat is None:
        print(f"[skipped] '{prefix}' not found as a column or as one-hot dummies in model_results_full.csv")
        return None

    dist = pd.DataFrame({
        'Full dataset (%)': full_cat.value_counts(normalize=True) * 100,
        'IF anomalies (%)': get_categorical(df_if, prefix).value_counts(normalize=True) * 100,
        'LOF anomalies (%)': get_categorical(df_lof, prefix).value_counts(normalize=True) * 100,
        'Both (%)': get_categorical(df_both, prefix).value_counts(normalize=True) * 100,
    }).round(2).fillna(0.0)
    dist = dist.sort_values('Full dataset (%)', ascending=False)
    print(f"\n{label} distribution: dataset vs anomalies (%)")
    display(dist)
    return dist


# ### 6.1 Property type

# In[72]:


property_type_dist = category_distribution('property_type', 'Property type')


# ### 6.2 Region

# In[73]:


region_dist = category_distribution('region', 'Region')


# ## 7. Numerical characteristics of anomalies
# 
# Compare medians of the main numeric variables across groups. The median is used
# throughout given the strongly skewed distributions already observed for price and
# surface area. Only variables actually present in `model_results_full.csv` are
# included.
# 

# In[74]:


candidate_vars = [
    'log_price', 'log_sqm', 'num_rooms', 'num_bathrooms',
    'price_per_sqm', 'sqm_per_room', 'baths_per_room', 'discount_pct',
    'price_relative_to_type', 'price_relative_to_province'
]
numeric_vars = [v for v in candidate_vars if v in df_results.columns]
missing_vars = [v for v in candidate_vars if v not in df_results.columns]
if missing_vars:
    print(f"[note] Not present in model_results_full.csv, skipped: {missing_vars}")

numeric_profile = pd.DataFrame({
    'Dataset (median)': df_results[numeric_vars].median(),
    'IF (median)': df_if[numeric_vars].median(),
    'LOF (median)': df_lof[numeric_vars].median(),
    'Both (median)': df_both[numeric_vars].median(),
}).round(3)
display(numeric_profile)


# ## 8. Anomaly rates by segment
# 
# Rather than asking *"which category has the most anomalies?"*, we are focused on *"what percentage of each category is flagged as
# anomalous?"*.
# 

# In[51]:


def anomaly_rate_by_segment(prefix, label, min_n=0):
    cat = get_categorical(df_results, prefix)
    if cat is None:
        print(f"[skipped] '{prefix}' not found.")
        return None
    tmp = pd.DataFrame({
        prefix: cat,
        'is_if_anomaly': df_results['is_if_anomaly'],
        'is_lof_anomaly': df_results['is_lof_anomaly'],
    })
    grouped = tmp.groupby(prefix).agg(
        Total=('is_if_anomaly', 'size'),
        IF_anomalies=('is_if_anomaly', 'sum'),
        LOF_anomalies=('is_lof_anomaly', 'sum'),
    )
    grouped = grouped[grouped['Total'] >= min_n].copy()
    grouped['IF_rate'] = (grouped['IF_anomalies'] / grouped['Total'] * 100).round(2)
    grouped['LOF_rate'] = (grouped['LOF_anomalies'] / grouped['Total'] * 100).round(2)
    grouped = grouped.sort_values('IF_rate', ascending=False)
    print(f"\nAnomaly rate by {label} (min n={min_n})")
    display(grouped)
    return grouped


# In[52]:


property_type_rates = anomaly_rate_by_segment('property_type', 'property type')


# In[53]:


region_rates = anomaly_rate_by_segment('region', 'region')


# In[ ]:


fig, axes = plt.subplots(1, 2, figsize=(14, 5))
if property_type_rates is not None:
    property_type_rates['IF_rate'].sort_values(ascending=False).head(10).plot(kind='bar', color='darkred', ax=axes[0])
    axes[0].set_title('IF anomaly rate by property type (top 10)')
    axes[0].set_ylabel('% anomalies')
if region_rates is not None:
    region_rates['IF_rate'].sort_values(ascending=False).head(10).plot(kind='bar', color='steelblue', ax=axes[1])
    axes[1].set_title('IF anomaly rate by region (top 10)')
    axes[1].set_ylabel('% anomalies')
plt.tight_layout()
plt.savefig(FIG_DIR / "IF_anomalies_by_property_type.png", dpi=150)
#plt.show()


# In[ ]:


fig, axes = plt.subplots(1, 2, figsize=(14, 5))
if property_type_rates is not None:
    property_type_rates['LOF_rate'].sort_values(ascending=False).head(10).plot(kind='bar', color='darkred', ax=axes[0])
    axes[0].set_title('LOF anomaly rate by property type (top 10)')
    axes[0].set_ylabel('% anomalies')
if region_rates is not None:
    region_rates['LOF_rate'].sort_values(ascending=False).head(10).plot(kind='bar', color='steelblue', ax=axes[1])
    axes[1].set_title('LOF anomaly rate by region (top 10)')
    axes[1].set_ylabel('% anomalies')
plt.tight_layout()
plt.savefig(FIG_DIR / "LOF_anomalies_by_property_type.png", dpi=150)
#plt.show()


# ## 9. Business-rule validation
# 
# Business-rule flags (`extreme_price_high`, `extreme_price_low`,
# `suspected_placeholder_sqm`, `extreme_price_per_sqm`, `excess_bathrooms`,
# `tiny_villa`, `huge_apartment`, ...) were deliberately **excluded from `X`** in
# Notebook 1 to avoid leakage. They are loaded here only as an **external reference**
# to see how much the unsupervised models agree with hand-crafted heuristics — not as
# ground truth.
# 
# For each rule we report two different overlap measures:
# - **Coverage**: of the listings flagged by the rule, what % was also flagged by the model.
# - **Overlap rate**: of the listings flagged by the model, what % also matches the rule.
# 
# Neither is called "precision" or "recall" in the strict sense, since there is no
# ground truth for anomalies.
# 

# In[55]:
# Carga de las reglas de negocio desde el dataset procesado
business_rules_path = ROOT_DIR / "data" / "processed" / "dataset_anomaly_detection_ready.csv"
fallback_rules_path = ROOT_DIR / "data" / "business_rule_flags.csv"

business_rule_cols = [
    'extreme_price_high', 'extreme_price_low', 'suspected_placeholder_sqm',
    'extreme_price_per_sqm', 'excess_bathrooms', 'tiny_villa', 'huge_apartment',
    'overcrowded_layout', 'any_flag'
]

if business_rules_path.exists():
    df_rules = pd.read_csv(business_rules_path, sep=";")
    df_rules['id'] = df_rules['id'].astype(str)
    df_results['id'] = df_results['id'].astype(str)
    
    cols_to_merge = ['id'] + [c for c in business_rule_cols if c in df_rules.columns]
    df_merged = df_results.merge(df_rules[cols_to_merge], on='id', how='left')
    available_rules = [c for c in business_rule_cols if c in df_merged.columns]
elif fallback_rules_path.exists():
    df_rules = pd.read_csv(fallback_rules_path, sep=";")
    df_rules['id'] = df_rules['id'].astype(str)
    df_results['id'] = df_results['id'].astype(str)
    
    cols_to_merge = ['id'] + [c for c in business_rule_cols if c in df_rules.columns]
    df_merged = df_results.merge(df_rules[cols_to_merge], on='id', how='left')
    available_rules = [c for c in business_rule_cols if c in df_merged.columns]
else:
    print(f"[skipped] No se encontró archivo de reglas de negocio en {business_rules_path}")
    df_merged = df_results.copy()
    available_rules = []

print(f"Business rules available for validation: {available_rules}")


# ### 9.1 Model anomalies vs business rules

# In[56]:


if available_rules:
    overlap_rows = []
    for rule in available_rules:
        rule_flagged = df_merged[df_merged[rule] == 1]
        n_rule = len(rule_flagged)

        if_coverage = rule_flagged['is_if_anomaly'].mean() * 100 if n_rule else np.nan
        lof_coverage = rule_flagged['is_lof_anomaly'].mean() * 100 if n_rule else np.nan
        both_coverage = (rule_flagged['is_if_anomaly'] & rule_flagged['is_lof_anomaly']).mean() * 100 if n_rule else np.nan

        if_flagged = df_merged[df_merged['is_if_anomaly']]
        lof_flagged = df_merged[df_merged['is_lof_anomaly']]
        both_flagged = df_merged[df_merged['is_if_anomaly'] & df_merged['is_lof_anomaly']]

        if_overlap_rate = if_flagged[rule].mean() * 100 if len(if_flagged) else np.nan
        lof_overlap_rate = lof_flagged[rule].mean() * 100 if len(lof_flagged) else np.nan
        both_overlap_rate = both_flagged[rule].mean() * 100 if len(both_flagged) else np.nan

        overlap_rows.append({
            'Business rule': rule, 'n_flagged_by_rule': n_rule,
            'IF coverage (%)': round(if_coverage, 1), 'LOF coverage (%)': round(lof_coverage, 1),
            'Both coverage (%)': round(both_coverage, 1),
            'IF overlap rate (%)': round(if_overlap_rate, 1), 'LOF overlap rate (%)': round(lof_overlap_rate, 1),
            'Both overlap rate (%)': round(both_overlap_rate, 1),
        })

    business_rule_overlap = pd.DataFrame(overlap_rows)
    display(business_rule_overlap)
else:
    business_rule_overlap = pd.DataFrame()
    print("No business-rule columns available: skipping overlap table.")


# ## 10. Consensus anomalies
# 
# Observations **consistently identified as anomalous by both methods** (not to be
# described as "true anomalies", since there is no ground truth).
# 

# In[57]:


df_results['consensus_anomaly'] = df_results['is_if_anomaly'] & df_results['is_lof_anomaly']
df_results['agreement_group'] = np.select(
    [
        df_results['is_if_anomaly'] & df_results['is_lof_anomaly'],
        df_results['is_if_anomaly'] & ~df_results['is_lof_anomaly'],
        ~df_results['is_if_anomaly'] & df_results['is_lof_anomaly'],
    ],
    ['Both', 'IF only', 'LOF only'],
    default='Neither'
)

display(df_results['agreement_group'].value_counts().to_frame('n_listings'))
consensus_anomalies = df_results[df_results['consensus_anomaly']].copy()


# ## 11. Ranking of the most anomalous observations

# In[58]:


display_cols = [c for c in ['id', 'name', 'property_type', 'province', 'sqm', 'price',
                             'price_per_sqm', 'if_score', 'lof_score'] if c in df_results.columns or c in ['property_type', 'province']]
# resolve property_type/province if they only exist as dummies
for cat_col in ['property_type', 'province']:
    if cat_col not in df_results.columns:
        resolved = get_categorical(df_results, cat_col)
        if resolved is not None:
            df_results[cat_col] = resolved
display_cols = [c for c in ['id', 'name', 'property_type', 'province', 'sqm', 'price',
                             'price_per_sqm', 'if_score', 'lof_score'] if c in df_results.columns]


# ### 11.1 Top Isolation Forest anomalies

# In[59]:


top_if_anomalies = df_results.sort_values('if_score', ascending=False).head(20)[display_cols]
display(top_if_anomalies)


# ### 11.2 Top LOF anomalies

# In[60]:


top_lof_anomalies = df_results.sort_values('lof_score', ascending=False).head(20)[display_cols]
display(top_lof_anomalies)


# ### 11.3 Top consensus anomalies
# 
# IF and LOF scores are not directly comparable in magnitude (Section 3.3), so a
# joint ranking is built from **percentiles** of each score rather than raw values.
# 

# In[61]:


df_results['if_percentile'] = df_results['if_score'].rank(pct=True) * 100
df_results['lof_percentile'] = df_results['lof_score'].rank(pct=True) * 100
df_results['combined_rank'] = (df_results['if_percentile'] + df_results['lof_percentile']) / 2

consensus_anomalies = df_results[df_results['consensus_anomaly']].copy()
top_consensus_anomalies = consensus_anomalies.sort_values('combined_rank', ascending=False).head(20)[
    display_cols + ['if_percentile', 'lof_percentile', 'combined_rank']
]
display(top_consensus_anomalies)


# ## 12. Case studies
# 
# A handful of representative cases, selected programmatically. Interpret the actual
# listing details once this cell is run on the real data — the selection logic is
# what matters here, not fixed numbers.
# 

# In[62]:


case_studies = {}

if 'price_per_sqm' in df_results.columns:
    case_studies['Case 1: Extreme price per square metre'] = df_results.sort_values('price_per_sqm', ascending=False).head(3)

if {'baths_per_room', 'sqm_per_room'}.issubset(df_results.columns):
    structural_outlier_score = df_results['baths_per_room'].abs() + df_results['sqm_per_room'].abs()
    case_studies['Case 2: Unusual accommodation structure'] = (
        df_results.assign(_structural_score=structural_outlier_score)
                  .sort_values('_structural_score', ascending=False).head(3)
                  .drop(columns='_structural_score')
    )

if 'price_relative_to_type' in df_results.columns:
    case_studies['Case 3: Contextual anomaly (relative to type/province)'] = (
        df_results[df_results['is_if_anomaly'] | df_results['is_lof_anomaly']]
        .sort_values('price_relative_to_type', ascending=False).head(3)
    )

for title, frame in case_studies.items():
    print(f"\n{'='*80}\n{title}\n{'='*80}")
    display(frame[display_cols])


# ## 13. Interesting disagreement cases
# 
# Listings flagged by only one of the two models. These help illustrate the
# conceptual difference between the algorithms — **Isolation Forest** isolates
# observations that are globally rare, while **LOF** flags observations that are
# locally sparse relative to their neighbourhood. No claim is made about which
# method is "correct"; the goal is to understand *why* they can disagree.
# 

# In[63]:


if_only_cases = df_results[df_results['agreement_group'] == 'IF only'].sort_values('if_score', ascending=False).head(10)
lof_only_cases = df_results[df_results['agreement_group'] == 'LOF only'].sort_values('lof_score', ascending=False).head(10)

print("IF-only cases (top 10 by if_score):")
display(if_only_cases[display_cols])

print("\nLOF-only cases (top 10 by lof_score):")
display(lof_only_cases[display_cols])


# ## 14. Final validation summary

# In[65]:


final_summary = pd.DataFrame([
    {'Aspect': 'Dataset analysed', 'Result': f"{n_rows:,}"},
    {'Aspect': 'IF anomalies', 'Result': f"{n_if_anomalies:,} ({n_if_anomalies / n_rows:.2%})"},
    {'Aspect': 'LOF anomalies', 'Result': f"{n_lof_anomalies:,} ({n_lof_anomalies / n_rows:.2%})"},
    {'Aspect': 'Agreement (both)', 'Result': f"{len(intersection):,}"},
    {'Aspect': 'Jaccard similarity', 'Result': f"{jaccard:.4f}"},
    {'Aspect': 'IF-only', 'Result': f"{len(if_only):,}"},
    {'Aspect': 'LOF-only', 'Result': f"{len(lof_only):,}"},
    {'Aspect': 'Spearman rank correlation (IF vs LOF)', 'Result': f"{rank_corr:.4f}"},
    {'Aspect': 'Business-rule overlap', 'Result': "see Section 9" if available_rules else "not available"},
])
display(final_summary)


# The results show that both algorithms identify a subset of observations with
# characteristics that differ from the general accommodation population. The
# agreement between Isolation Forest and LOF provides an additional indication of
# consistency, while the disagreement between both methods highlights observations
# whose anomalous nature depends on the detection perspective. The comparison with
# business rules further provides an interpretable reference for assessing whether
# detected observations correspond to extreme prices, unusual accommodation
# characteristics, or contextual deviations.
# 

# ## 15. Export results for the TFM
# 
# Save the reusable tables produced above so the write-up (and any further
# exploration) does not require re-running the full notebook.
# 

# In[68]:
exports = {
    'anomaly_analysis_summary.csv': final_summary,
    'anomaly_model_comparison.csv': summary_table,
    'anomaly_by_property_type.csv': property_type_rates,
    'anomaly_by_region.csv': region_rates,
    'business_rule_overlap.csv': business_rule_overlap,
    'top_if_anomalies.csv': top_if_anomalies,
    'top_lof_anomalies.csv': top_lof_anomalies,
    'consensus_anomalies.csv': consensus_anomalies,
    'disagreement_cases.csv': pd.concat([
        if_only_cases.assign(disagreement_type='IF only'),
        lof_only_cases.assign(disagreement_type='LOF only')
    ]) if 'if_only_cases' in locals() and 'lof_only_cases' in locals() else None,
}

print("=" * 60)
print("EXPORTING RESULTS")
print("=" * 60)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

for filename, frame in exports.items():
    if frame is None or (hasattr(frame, 'empty') and frame.empty):
        print(f"Skipped (no data): {filename}")
        continue
    path = OUTPUT_DIR / filename
    frame.to_csv(path, sep=";", index=False, encoding="utf-8")
    print(f"Saved: {path}")

